### ISSUE TITLE
Please change that people can contact everyone (mutual friends or opt-in by an account only)

### ISSUE THREAD

**Issue by rduinmaijer** [humhub/mail#136]
Please change that people can contact everyone (mutual friends or opt-in by an account only).

Now everyone can message everyone, this is not really useful in the real world ;) 

Please make it optional that we can choose that mutual friends can message each other and / or an opt-in option per account so that people can send them a message when they allow it 

By default do not allow mass-messaging everyone.

**Comment by buddh4** [comment]
You can overwrite default permissions by configuration, see http://docs.humhub.org/admin-advanced-configuration.html#overwrite-default-permissions

`humhub\modules\mail\permissions\SendMail`

and 

`humhub\modules\mail\permissions\StartConversation`

Since HumHub often is used as intranets or smaller collaboration based communties the permissions often don't have to bee that strict. I think a global setting as `strict mode` or `non strict mode` should be implemented which can effect the default permissions etc.

**Comment by Ace2213** [comment]
I wasn't able to find anything to modify in StartConversation.php, but in SendMail.php I commented out Users as a default allowed group. The result is that non-friends in the user picker were appearing greyed out and un-selectable. 

I don't think they should appear at all, which would require a change to the user picker itself.

Additionally, there's currently no way of allowing users to contact "mutual friends", which would have to be added as a universal user group.

While we're on the subject, what does the mail permission do? In my testing, it doesn't stop you from receiving messages.
![image](https://user-images.githubusercontent.com/12226710/68203136-eba93d80-ffa3-11e9-930e-014fc85f636c.png)
