### ISSUE TITLE
Add message events to conversation (e.g. Joined/Left)

### ISSUE THREAD

**Issue by buddh4** [humhub/mail#187]
Message events as:

- User joined
- User left
- Title edit

**Comment by orangiene** [comment]
![Messages#187-v01](https://user-images.githubusercontent.com/62644500/146034668-c74f091e-f1fb-4591-9037-accddbc16331.jpg)
![Messages#187-v02](https://user-images.githubusercontent.com/62644500/146034692-61369337-9da7-4829-ba9f-ebd13e1a1165.jpg)
![Messages#187-Change-title](https://user-images.githubusercontent.com/62644500/146034706-c564389e-ab44-4157-b9ed-480587ee6a49.jpg)


hello :)
I would give my text messages a different background color than the text messages of the other users in the chat. 
this is better for the eye to distinguish and more pleasant to read. 

Otherwise I have created two color variants for the messages when someone leaves the chat, etc..

Should the original creator of the message be able to remove users?
