### ISSUE TITLE
Press Enter to send (Optional)

### ISSUE THREAD

**Issue by ArchBlood** [humhub/mail#189]
I like how the new beta is as of now, only problem is that you have to use `Tab` + `Enter` to send or manually click the button, traditionally just pressing `Enter` would be enough of an action to send a message and could be configured by the user as a user preference which I think would be much easier and common for people to use and understand

There is also about a 5-10 second delay on getting a message reply from someone, which I can understand as being the normal but isn't real-time for today's standards :thinking:

**Comment by buddh4** [comment]
`Tab + Enter` and  `Ctrl + s` can be used to submit as with other richtext fields. I think there should be a general richtext feature for this. Perhaps something like an options dropdown in the menu with an option to check `Submit on Enter`.

The message delay is due to using the live polling by default, you can try to switch to [push](https://github.com/humhub/humhub-pushservice) but unfortunately this is still in beta and we did not have the time for any further production tests.

In HumHub 1.6.3 the module should be able to shorten the poll delay from the default 15 to 5sec. In the future we may could set a 2 seconds poll delay or something.

**Comment by spoorun** [comment]
See also: https://github.com/humhub/humhub/issues/1454
