### ISSUE TITLE
Tag individual messages by topic or subject

### ISSUE THREAD

**Issue by spoorun** [humhub/mail#211]
Humhub has a built-in Topic system.

In the modern paradigm of viewing messages by conversation with a user/group rather than subject line, 
(as will hopefully be implemented with: https://github.com/humhub/humhub-modules-mail/issues/192 ),
finding individual relevant messages by search will be even more crucial.

Add a tag symbol to messages to add  topics to a message. Display topics in top right corner of messages in bubbles, allow removal with an 'x'.

**Comment by buddh4** [comment]
The latest module version has a tag system, we do not use topics since topics is a content only concept and messages are no content in HumHub.

![grafik](https://user-images.githubusercontent.com/9800854/108088017-48851600-7078-11eb-86b7-77acf4acf025.png)

Note those tags are managed on user level (you probably requested conversation level tags instead):

![grafik](https://user-images.githubusercontent.com/9800854/108088154-6f434c80-7078-11eb-87ca-b03581c89841.png)
