### ISSUE TITLE
Message notifications vs Conversation notifications ?

### ISSUE THREAD

**Issue by superseby2** [humhub/mail#230]
One of my user had in his notifications settings : 

 Notifications when someone sends you a message : checked for emails.
 Notifications when someone opens a new conversation : unchecked for emails.

As a result, he was receiving no messages at all.

While testing I am realizing that the if notifications for new conversation is not checked for emails, no email is sent out. And having Notifications for messages checked or not for emails does not change anything. 

[ tested on a new conversation and on existing conversation ]

Could you please clarify the 2 notifications setting ? And maybe confirm there is a bug here?

Thx !

**Comment by TorWaG77** [comment]
I fear, it is a bug. It worked correctly in a former version of mail-module. [https://community.humhub.com/content/perma?id=244797](url) Torsten

**Comment by superseby2** [comment]
Thx ! Hopefully it will be moved up soon !

**Comment by yurabakhtin** [comment]
@luke- I confirm the module used only the single notification "**Conversation** Receive Notifications when someone opens a new conversation.".

I have fixed this in PR https://github.com/humhub/mail/pull/237.
Please note when user creates a conversation we create in DB the same Message Entry like a new message is posted for already existing Conversation. So for case when notification "**Conversation**" is disabled but the notification "**Message**" is enabled then user will receive a notification like just Message Entry was created even if really it was a creating of new Conversation, i.e. user will see email with text like `User Name sent you a new message in "ABC"` instead of `User Name created a new conversation "ABC"` in order to don't confuse the user. I hope this is correct.

<img width="1391" alt="notifications" src="https://user-images.githubusercontent.com/6995524/132371809-6d25e26a-fd19-4a89-babc-ada9d2846184.png">

**Comment by luke-** [comment]
@yurabakhtin Thanks. Good point, if the user disables only the "Conversion" notification. Are there any tests for this yet? If not, it would be good if you could add 1-2 here.

**Comment by yurabakhtin** [comment]
@luke- I have added 4 tests for each different case of the 2 notification settings:
- Both notifications are disabled
- Only notification "Conversation" is enabled
- Only notification "Message" is enabled
- Both notifications are enabled

Commit https://github.com/humhub/mail/pull/237/commits/e5837052dc5ca83b5cedd9ee05116840dd5fb75b

**Comment by superseby2** [comment]
Even if I am late to the party ;) I can't help but think that this might be too fine-grained and still confusing for users. 
Can't we have only one notfication settings  for messages,  whether they are a new conversation or part of an already existing conversation?

**Comment by luke-** [comment]
@superseby2 That's right, might you like to open a new issue here? 

@yurabakhtin Thanks!
