### ISSUE TITLE
Notify attendees of a chat that another person has left the conversation

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#285]
When other User enter or leave a conversation, other attendees will be notified in the chat. The change will be displayed with the date and name that they left/entered the conversation. The style of this notifying message is different than the style of the conversation messages so that other attendees can see it is an informative message. It is designed like a white badge with semibold font-weight with a slight shaddow blur. please check figma for further detail.

![Bildschirmfoto 2023-01-24 um 16 47 53](https://user-images.githubusercontent.com/105652258/214544998-8bd6f81e-1447-4ca8-bbd8-c933491e3bf2.png)

**Comment by yurabakhtin** [comment]
@Eladnarlea What do you think if we will not show the date badge above new state messages?
I think the additional date badge will confuses, it would be better to display such state messages between normal messages like this:

![mail-state-badge](https://user-images.githubusercontent.com/6995524/218392565-dbfbfdbf-9573-4b4f-ae40-34006f2ae918.png)

**Comment by yurabakhtin** [comment]
@luke- I would dicsuss where we should store new state message:

- Easier way is to use the same table `message_entry` where normal messages are stored.
We just add a column like `type`:
  - `MessageEntry::TYPE_MESSAGE = 0` - For normal messages
  - `MessageEntry::TYPE_JOINED = 1` - For user joined action
  - `MessageEntry::TYPE_LEFT = 2` - For user left action
In such case we just use a different view for new types.
Of course db rows of new types will contain some columns as useless, like `content` will be empty.
- Another way is to create a new table, but in such cases we need to execute more complex sql queries in order to display the state (join/left) badges between normal messages.

I prefer first approach because I think the state messages may take less 1% of normal messages.
Do you agree?
Thanks.

**Comment by luke-** [comment]
@yurabakhtin Yes, the first approach is fine!

**Comment by Eladnarlea** [comment]
> @Eladnarlea What do you think if we will not show the date badge above new state messages? I think the additional date badge will confuses, it would be better to display such state messages between normal messages like this:

@yurabakhtin I am not quite sure if I got that right, so I tried to visualise another use case.

The "joined/ left"- Badge is not sticky to the bottom of the message. It is more like a message that is placed inside the chat course. I understand your concern but the hover effect to show the time/date the person has entered or left the conversation is not handy for mobile devices. The Time&Date notifications can also hold more chat actions rather than only one action. 
e.g.:

<img width="436" alt="Screen Shot 2023-02-13 at 9 37 09 AM" src="https://user-images.githubusercontent.com/105652258/218409832-a7ded3b6-db36-41f2-bc6f-658c6d79a14f.png">

Thank you for your suggestion! it has helped me to specify the use case! :)

**Comment by yurabakhtin** [comment]
@Eladnarlea 

> The "joined/ left"- Badge is not sticky to the bottom of the message. It is more like a message that is placed inside the chat course.

Got it.

> I understand your concern but the hover effect to show the time/date the person has entered or left the conversation is not handy for mobile devices

If you don't like the tooltip over the state message then we can don't display it, but please note I just show the sample view only because we already have this e.g. here:

![date-tooltip](https://user-images.githubusercontent.com/6995524/218422523-128b6953-2339-44a2-a98d-8fe2a0f0d174.png)

> The Time&Date notifications can also hold more chat actions rather than only one action.

Ok, thanks for the info, I think we will implement the new actions later.

**Comment by Eladnarlea** [comment]
I see. Please remove the hover tooltip option with the time&date display completely. Thank you!

<img width="708" alt="Screen Shot 2023-02-13 at 11 25 31 AM" src="https://user-images.githubusercontent.com/105652258/218433399-ac9c8935-48ce-4f95-a963-4f8e677e8c76.png">

**Comment by yurabakhtin** [comment]
@luke- @Eladnarlea Commit https://github.com/humhub/mail/pull/283/commits/707752e17d48adb2ee5c8834256008f6c9a24d80 for new user states:

![msg_user_states](https://user-images.githubusercontent.com/6995524/218479988-3735c8e8-9382-4e4f-a176-667cacc5418e.png)

**Comment by luke-** [comment]
@Eladnarlea Just updated your installation!

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- 

> I see. Please remove the hover tooltip option with the time&date display completely. Thank you!

Commit https://github.com/humhub/mail/pull/283/commits/dd402ee3de088f708dbc2fe548db9ad56026b3dc.

**Comment by Eladnarlea** [comment]
is this mistake only on your installation?

![Screen Shot 2023-02-14 at 8 15 55 AM](https://user-images.githubusercontent.com/105652258/218665775-ab434b09-755b-4901-9d13-275b81d67ddf.png)

> ![msg_user_states](https://user-images.githubusercontent.com/6995524/218479988-3735c8e8-9382-4e4f-a176-667cacc5418e.png)

**Comment by yurabakhtin** [comment]
@Eladnarlea Thanks for the notice, it is fixed in commit https://github.com/humhub/mail/pull/283/commits/dc65c209023606cbee9f0801393e28daa447a55e:

![fix_time_position](https://user-images.githubusercontent.com/6995524/218696137-d655230a-b7ec-44b8-a711-145a34bbc635.png)

It was broken on entry with single line text and with displayed user name, but please note now we have a bit more space between entry text and time because if the time info is moved up to 8px then it is ovelapped a posted image like my sample screenshot below. Let me know if I really should find a solution to keep the previous space between text and time and make it good view also with images:

![top_8px](https://user-images.githubusercontent.com/6995524/218698497-8ba4e1ee-3b12-4186-a7f5-9229c53ed92d.png)

**Comment by Eladnarlea** [comment]
this should do, thank you @yurabakhtin ! :)

**Comment by Eladnarlea** [comment]
One more thing @yurabakhtin, can you please make the padding top&bottom the same? Preferably take over the padding bottom height. thank you!

![Screen Shot 2023-02-14 at 11 58 07 AM](https://user-images.githubusercontent.com/105652258/218716317-ae7dedc3-b7b7-4509-a1a9-c90bbd8b357f.png)

**Comment by yurabakhtin** [comment]
@Eladnarlea Done:

![badge-space](https://user-images.githubusercontent.com/6995524/218723062-a697482f-3b50-49d5-ad3c-9aada78deb8a.png)
