### ISSUE TITLE
"-edited" information in speech bubble

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#290]
whenever someone edits a message, this specific message will be marked as edited in the right bottom corner. @luke- Proposal: we could also always display the time the message has been sent
![Bildschirmfoto 2023-01-25 um 13 12 06](https://user-images.githubusercontent.com/105652258/214560359-da88617e-6bbe-4324-b918-f38b511d0d11.png)

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- Commit https://github.com/humhub/mail/pull/283/commits/0e8cecfd7017899b8537e999be7f0bdb022ffd35:

![mail-time](https://user-images.githubusercontent.com/6995524/216300908-1445c4f0-c13e-41c0-a9db-fce68a566a37.png)

**Comment by Eladnarlea** [comment]
Well done! I really like the new Mail Module! :) I also think that the time and "edited" badge is a great feature.

For the Future: We could think of adding colors to the names


![Screen Shot 2023-02-02 at 2 41 40 PM](https://user-images.githubusercontent.com/105652258/216341157-beec6da7-83f9-4c79-8946-75b4f5f85505.png)

**Comment by Eladnarlea** [comment]
And one more thing: Can we place the time next to the text when it's a text that only goes over one line? the moment it is over two lines we should position it underneath the text.

![Screen Shot 2023-02-02 at 2 41 40 PM](https://user-images.githubusercontent.com/105652258/216341974-c82b2ae5-83f6-4bb0-be1c-5261aa7172e2.png)

like here:

![Screen Shot 2023-02-02 at 2 45 55 PM](https://user-images.githubusercontent.com/105652258/216342117-c2cd1ebc-21e8-4a8d-8351-a13d782f0bf0.png)

A´

**Comment by yurabakhtin** [comment]
@Eladnarlea 

> For the Future: We could think of adding colors to the names

Do you mean to assign each username some random color?

**Comment by yurabakhtin** [comment]
@luke- 

> And one more thing: Can we place the time next to the text when it's a text that only goes over one line? the moment it is over two lines we should position it underneath the text.

I have tried to implement this in commit https://github.com/humhub/mail/pull/283/commits/36b8b83f5408eeb2a7adbdd2364b6a50e1a02bb9, but please note I cannot find a solution how to reduce a space when there are 2 lines and more because it is impossible from CSS side, so please review how it looks on different screen sizes especially on small screens and let me know if I should revert to the style as it was before:

![time-1](https://user-images.githubusercontent.com/6995524/216542222-2c3bbb17-5dbc-4d28-bab3-0a3f14099b01.png)
![time-2](https://user-images.githubusercontent.com/6995524/216542220-377281a4-c9f8-4656-87b7-fb19f5f02d3d.png)
![time-3](https://user-images.githubusercontent.com/6995524/216542217-c581d59f-2979-4db2-ab1b-5d8a4c626baa.png)
![time-4](https://user-images.githubusercontent.com/6995524/216542214-77f59a2d-f178-4a04-a90b-cb826d675584.png)

**Comment by Eladnarlea** [comment]
> Do you mean to assign each username some random color?

exactely but we have to keep in mind that they will have to be with a certain saturation for readability, because the bubbles are in grey.

**Comment by yurabakhtin** [comment]
@Eladnarlea 

> > Do you mean to assign each username some random color?
> 
> exactely but we have to keep in mind that they will have to be with a certain saturation for readability, because the bubbles are in grey.

Commit https://github.com/humhub/mail/pull/283/commits/890cc381e643ccde10127f59ddab88294429c5f4:

![user-colors](https://user-images.githubusercontent.com/6995524/217238703-9c19e1bd-332b-464c-86c8-e4ed2c6a615d.png)

---

Please note I used colors from here https://www.w3schools.com/colors/colors_trends.asp except of several.
You can review full list of using colors and let me know if we should add or exclude some colors:

![palette](https://user-images.githubusercontent.com/6995524/217239057-13dd8a56-b1d7-4634-9980-ab1c80cf627a.png)

**Comment by Eladnarlea** [comment]
Nice, I really like it! What do you think @luke- ?

**Comment by luke-** [comment]
I like it. We can happily leave it as it is! @Eladnarlea
