### ISSUE TITLE
New Message Count in HTML Title not reset after Message was read

### ISSUE THREAD

**Issue by luke-** [humhub/mail#323]
We have recently added the number of unread message/mail module messages in addition to unread notifications. 

The number of read messages is not reset in the HTML title when a message has been read.

https://github.com/humhub/mail/commit/f84e77e9edcd0be4db42a402d079bc0ff5d43fd0#diff-d6c7626df8c770aca9c520e0a4a2bfc55eefc4a01127cda6ac03a12fe3038a71R48

**Comment by yuriimaz** [comment]
Tested sending, receiving and reading messages several times, but could not reproduce this problem.
Cases I checked:
- Changing the counter of unread conversations (COUC) when receiving a new message in a new conversation
- Changing the COUC when receiving a new message in an existing conversation
- The appearance of a new message indicator when receiving a new message in a conversation
- Changing the COUC when opening an unread conversation through the drop-down list in the top panel
- Changing the counter of unread conversations when opening an unread conversation through the list of conversations on the conversation page
- Changing the COUC after logout and re-login
- Changing the COUC after changing the recipient's time zone
- Changing the COUC when receiving a message from several conversation participants at the same time, if there are more than two participants in the conversation
- Changing the COUC for the added participant if they were added to an existing conversation

The counter changed correctly in all cases. Only in the last case did the added participant's COUC change, but the conversation in the list did not have a mark that it was a new conversation. Maybe it confuses users as to why the numbers don't match?

Maybe there are some other cases that need to be checked or are there any details as a result of which this problem was observed? Or maybe it is necessary to correct the problem described for the last case? But I think that this does not apply to this issue.

**Comment by luke-** [comment]
@yuriimaz Thanks for testing, I'll contact the original reporter for more details.

**Comment by luke-** [comment]
Here more Details: https://github.com/humhub/humhub-internal/issues/44

**Comment by luke-** [comment]
Fixed with Humhub 1.14.1
