### ISSUE TITLE
Deactivated users & messages/notifications

### ISSUE THREAD

**Issue by Semir1212** [humhub/mail#371]
If a conversation was created before a participant's account was deactivated, it is currently possible to write to them which triggers a notification. Deactivated users should not receive any notifications apart from maybe "account activated/deactivated".

**Comment by luke-** [comment]
It would probably be the best behavior if we also save notifications for deactivated users but skip emails/push/browser notifications. This would allow re-activated users to see them again later. 
 
@yurabakhtin Can you please check?

**Comment by yurabakhtin** [comment]
@luke- 

> It would probably be the best behavior if we also save notifications for deactivated users but skip emails/push/browser notifications. This would allow re-activated users to see them again later.

I see it should works like this for all notifications extended from core `BaseNotification` because here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/notification/components/NotificationManager.php#L95-L97 we skip a sending if `$user->status != User::STATUS_ENABLED`.
However this module `mail` doesn't use the core `BaseNotification` so I have fixed this in PR https://github.com/humhub/mail/pull/372.
