### ISSUE TITLE
Timezone Issue

### ISSUE THREAD

**Issue by FernandoHCFaria** [humhub/mail#429]
My server (WHM) timezone is set to UTC. In my humhub instance, I have set the timezone to UTC -3 (America/São_Paulo). In a test, I sent a PM message and the time was wrong. My profile (and all users' profiles) are set by default to UTC -3 as well. Im already using Humhub 1.17 beta 2.

See the screenshots below:
![error1](https://github.com/user-attachments/assets/5c8ea8b6-e986-4d5f-8007-8bbdf926a9f8)
![unnamed](https://github.com/user-attachments/assets/f9a8b054-df89-457c-8338-19bc20b4bc26)

https://community.humhub.com/s/general-discussion/?contentId=282534&commentId=50824

**Comment by luke-** [comment]
@yurabakhtin Somehow related to our latest changes in v.17?

**Comment by yurabakhtin** [comment]
@luke- Yes, the bug is related to this PR https://github.com/humhub/humhub/pull/7243.

I have detected the time is printed with different ways:

- `Yii::$app->formatter->asTime($this->entry->created_at, 'short')`
- `Yii::$app->formatter->asTime(new DateTime($this->entry->created_at), 'short')`

In first case I see the time zone `Yii::$app->formatter->defaultTimeZone` is used to parse the string date like `2024-11-22 19:47:12`.
In second case the time zone `Yii::$app->timeZone` is used on init the class `new DateTime()`, so the `formatter->defaultTimeZone` is not used for parsing because it is already a `DateTime` object.

On my test server the time zones were different on `develop-v1.17`, therefore the results were different.
On `master-v1.16` it works with same results as expected.

As we set `Yii::$app->timeZone` from new setting `serverTimeZone`, then I have done to use the same value for the `Yii::$app->formatter->defaultTimeZone` and now I have the same values in these both cases.
Please merge the PR https://github.com/humhub/humhub/pull/7316.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
